= Connectors
:toc:
:toclevels: 1

== Overview

The SysBot Connectors Library is a collection of connectors designed to facilitate communication between various systems. This library provides a set of reusable components that can be easily integrated into your projects to enable seamless data exchange and automation.

.Supported protocols
[options="header"]
|===
| Protocol | Description | Parameters
| SSH | Secure Shell | host(str), port(int), login(str), password(str)
| WinRM | Windows Remote Management | host(str), port(int), login(str), password(str)
| Redfish | Redfish API | host(str), port(int), login(str), password(str)
| Ios | Cisco IOS | host(str), port(int), login(str), password(str)
| NeoRest | Neo REST API | host(str), port(int), login(str), password(str)
| VMware vSphere | VMware vSphere API | host(str), port(int), login(str), password(str)
|===

== Quickstart

=== Installation

[IMPORTANT] 
.Pre-requisite
====
Python 3.7 or higher see: https://www.python.org/downloads/[Python Downloads]
====

[source,shell]
----
python -m pip install sysbot
----

=== Basic Usage

[source,python]
----
from sysbot.connectors import ConnectorInterface <1>

conn = ConnectorInterface() <2>
conn.open_session('test', 'ssh', '10.0.0.1', 22, 'admin', 'password') <3>
conn.execute_command('test', 'ls -l') <4>
conn.close_all_sessions() <5>
----
<1> Import the ConnectorInterface class.
<2> Initialize a new ConnectorInterface instance.
<3> Open a new session with the specified parameters with alias 'test'.
<4> Execute a command on the session with alias 'test'.
<5> Close all active sessions.

== Design

=== Responsibilities

* Serve as the centralized interface for establishing and managing connections to target systems.
* Provide an abstraction layer to unify interactions with diverse communication protocols.
* Enable execution of commands and retrieval of results from various systems.
* Handle secure session management, including session opening, command execution, and cleanup.
* Provide the capacity to make multiple SSH tunneling session

=== Interaction

* Invokes ConnectorInterface to establish sessions or execute commands on target systems.
* Uses aliases to manage and track multiple connections.
* Dynamically delegates session management and command execution to protocol-specific implementations (e.g., Ssh, Winrm, Redfish, etc.).
* Maintains a cache of active sessions to optimize resource usage and prevent redundant connections.

=== Data flow

image::connectors_dataflow.svg[Data flow diagram, 500, 500]